import Header from "@/components/layout/Header/Header";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import { ThemeProviders } from "@/theme/ThemeProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Web3Modal } from '../context/web3modal';
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className='h-full'>
      <body className={
        cn("bg-background h-full flex flex-col")
      }>
        <Web3Modal>
          <ThemeProviders
            attribute="class"
            defaultTheme="dark"
            enableSystem
          >
            <Header />
            <div className='flex-1 max-w-7xl m-auto w-[90%]'>
              {children}
            </div>
            <Toaster />
          </ThemeProviders>
        </Web3Modal>
      </body>
    </html>
  );
}
